version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      PORT: 8080
    volumes:
      - /var/www/api
    ports:
      - "3000:3000"
    expose:
      - "3000"
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "9080"
