# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad05796fd11dde779ba5ba12417a81ec881c5205d53e0ae32315174507fc8c754f66adbb42dc78e91529737d9736ca7f91a700784bb86e3529ca3b0b7b813bd8

test:
  secret_key_base: c2ee685536bfb257c7a5f0ad70e01e4cd40be760638dd479d2cdf472de930dc47f8e8564070cf7a23e57c8a0ac88050d329f52d12d5341b7e369a9949b5934cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
